# lambda: 익명함수
- 이름이 없는 함수
- 정렬, 크기비교, 필터링
- parital: 매개변수의 값(함수 인자)을 고정하는 사용

In [1]:
def my_fn(a, b):
  return a + b
my_fn

<function __main__.my_fn>

In [2]:
lambda a, b: a + b

<function __main__.<lambda>>

In [4]:
my_fn(1, 2)

3

In [5]:
(lambda a, b: a + b)(1, 2)

3

In [6]:
a = lambda a, b: a + b # 일급 클래스: 변수 저장, 함수의 인자, 반환값
a

<function __main__.<lambda>>

In [7]:
a(1, 2)

3

# 익명함수의 활용
- min & max
- sorted
- map
- filter
- reduce (사용 지양, 사용처 딱 정해져 있다.)
- partial + 알파 

- min(a, b, c...)
- min(iterable[, key])
- max(a, b, c...)
- max(iterable[, key])

**iterable**: list, set, tuple, dict.keys(), dict.values()

In [8]:
min(3, 2)

2

In [9]:
min([3, 4, 5])

3

In [10]:
blackpink = [
  {
    "name": "지수",
    "age": 25,
    "height": 162
  },
  {
    "name": "제니",
    "age": 24,
    "height": 163
  },
  {
    "name": "로제",
    "age": 23,
    "height": 168
  },
  {
    "name": "리사",
    "age": 24,
    "height": 166.5
  },
]

In [12]:
min(blackpink, key=lambda m:m['age'])

{'age': 23, 'height': 168, 'name': '로제'}

In [13]:
max(blackpink, key=lambda m:m['age'])

{'age': 25, 'height': 162, 'name': '지수'}

In [16]:
min([[1, 0], [2,0]])

[1, 0]

In [21]:
min([1, 0], [2, 0], key=lambda elem:elem[0]) # == min([1, 0], [2, 0])

[1, 0]

sorted:

- iterable: 정렬의 대상
- key: 비교 대상 정의
- reverse: False (오름차순) / True (내림차순)

In [28]:
import numpy as np
my_list = list(np.random.randint(0, 101, 8))
my_list

[33, 93, 40, 97, 2, 77, 96, 75]

In [29]:
# my_list.sort()
# my_list

In [30]:
sorted(my_list)

[2, 33, 40, 75, 77, 93, 96, 97]

In [31]:
my_list

[33, 93, 40, 97, 2, 77, 96, 75]

In [32]:
sorted(blackpink)

TypeError: ignored

In [33]:
sorted(blackpink, key=lambda m:m['age'])

[{'age': 23, 'height': 168, 'name': '로제'},
 {'age': 24, 'height': 163, 'name': '제니'},
 {'age': 24, 'height': 166.5, 'name': '리사'},
 {'age': 25, 'height': 162, 'name': '지수'}]

In [35]:
sorted(blackpink, key=lambda m:m['height'], reverse=True)

[{'age': 23, 'height': 168, 'name': '로제'},
 {'age': 24, 'height': 166.5, 'name': '리사'},
 {'age': 24, 'height': 163, 'name': '제니'},
 {'age': 25, 'height': 162, 'name': '지수'}]

# Map과 Filter
- map: iterable (collections) 각각의 원소에 동일한 작업을 수행
- filter: 필터링

In [36]:
my_animals = ["cat", "dog", "tiger", "snake", "cow"]
my_animals

['cat', 'dog', 'tiger', 'snake', 'cow']

In [41]:
"cat".capitalize()

'Cat'

In [43]:
list(map(lambda s:s.capitalize(), my_animals))

['Cat', 'Dog', 'Tiger', 'Snake', 'Cow']

In [44]:
map(lambda s:s.capitalize(), my_animals)

In [45]:
my_nums = list(range(1, 11))
my_nums

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [47]:
list(map(lambda x:x+1, my_nums))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [48]:
for num in map(lambda x:x+1, my_nums):
  print(num)

2
3
4
5
6
7
8
9
10
11


In [54]:
list(filter(lambda n:n==5, my_nums))

[5]

In [51]:
my_nums[::2]

[1, 3, 5, 7, 9]

In [52]:
my_nums[1::2]

[2, 4, 6, 8, 10]

In [53]:
my_nums[::3]

[1, 4, 7, 10]

In [57]:
list(filter(lambda s:'c' in s, my_animals))

['cat', 'cow']

- 내장 함수: 설치하지 않고 사용가능
- 패키지: 설치하지 않고 사용가능 + 설치

In [59]:
import collections 

https://github.com

- requests
- beautifulsoup
- ...

# Reduce 

- reduce(function, iterable[, initializer])


In [60]:
from functools import reduce

In [61]:
my_list = list(range(1, 6))
my_list

[1, 2, 3, 4, 5]

In [62]:
reduce(lambda x, y: x+y, my_list) # ((((1 + 2) + 3) + 4 ) + 5)

15

In [63]:
reduce(lambda x, y: x*y, my_list)

120

In [64]:
# Counter
my_data = ['a', 'a', 'a', 'b', 'b', 'c', 'c', 'c']
reduce(lambda a, b:a.update({b:a.get(b, 0)+1}) or a, my_data, {})

{'a': 3, 'b': 2, 'c': 3}

In [67]:
from collections import Counter
my_counter = Counter(my_data)
my_counter

Counter({'a': 3, 'b': 2, 'c': 3})

In [68]:
my_counter.update(['c'])

In [69]:
my_counter

Counter({'a': 3, 'b': 2, 'c': 4})

# Partial
- function
- *args: 왼쪽 위치 인자부터 정의
- *kwargs

In [73]:
from functools import partial

In [72]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [75]:
sum([1, 2, 3], 15)

21

In [76]:
sum([1, 3, 5, 7], 15)

31

In [78]:
my_sum = partial(sum, 15)

In [79]:
my_sum([1 ,2 ,3])

TypeError: ignored

In [81]:
help(pow) # x**y

Help on built-in function pow in module builtins:

pow(x, y, z=None, /)
    Equivalent to x**y (with two arguments) or x**y % z (with three arguments)
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [83]:
pow(2, 3) # 2**3, 2**n

8

In [84]:
pow(2, 4)

16

In [85]:
pow(2, 5)

32

In [87]:
my_pow = partial(pow, 2)
my_pow

functools.partial(<built-in function pow>, 2)

In [88]:
my_pow(3)

8

In [89]:
my_pow(4)

16

In [90]:
my_pow(5)

32

In [102]:
my_pow1 = partial(pow, 2, 5)
my_pow1

functools.partial(<built-in function pow>, 2, 5)

In [92]:
my_pow1()

32

In [93]:
my_sum = lambda x:sum(x, 15)
my_sum

<function __main__.<lambda>>

In [94]:
my_sum([1, 2, 3, 4])

25

- numpy array
  - 행렬
- python3 list

In [96]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [100]:
my_array = np.zeros((2, 1))
my_array + 1

array([[1.],
       [1.]])

In [101]:
[2,3]*3

[2, 3, 2, 3, 2, 3]

In [ ]:
help(np.random.randint)

In [111]:
np.random.randint(1, 47, size=6)

array([16,  4,  5, 39, 18, 42])

In [112]:
my_ran = partial(np.random.randint, 1, size=6)
my_ran

functools.partial(<built-in method randint of numpy.random.mtrand.RandomState object at 0x7fad03c67050>, 1, size=6)

In [113]:
my_ran(55)

array([20, 28, 19, 32, 39,  3])

In [114]:
my_ran(46)

array([35,  8,  1, 23, 11, 35])